### ISSUE TITLE
TypeError: telnet is not a constructor

### ISSUE THREAD

**Issue by lordchris78** [Martvvliet/homebridge-denon-heos#100]
TypeError: telnet is not a constructor
    at receiver.connectTelnet (/volume2/homebridge/node_modules/homebridge-denon-heos/index.js:579:27)
    at receiver.startConfiguration (/volume2/homebridge/node_modules/homebridge-denon-heos/index.js:350:9)
    at Request._callback (/volume2/homebridge/node_modules/homebridge-denon-heos/index.js:326:11)
    at self.callback (/volume2/homebridge/node_modules/homebridge-denon-heos/node_modules/request/request.js:185:22)
    at Request.emit (node:events:514:28)
    at Request.onRequestError (/volume2/homebridge/node_modules/homebridge-denon-heos/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    
    and restaring, i have no idee

**Comment by tinkerer9** [comment]
Check your receiver IP address.
