### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by morphix9** [Martvvliet/homebridge-denon-heos#32]
Hey, looks like the plugin is not working.

`Unhandled rejection Error: socket not writable
    at /usr/lib/node_modules/homebridge-denon-heos/node_modules/telnet-client/lib/index.js:260:16
    at Promise._execute (/usr/lib/node_modules/homebridge-denon-heos/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/homebridge-denon-heos/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/lib/node_modules/homebridge-denon-heos/node_modules/bluebird/js/release/promise.js:103:10)
    at Telnet.send (/usr/lib/node_modules/homebridge-denon-heos/node_modules/telnet-client/lib/index.js:216:12)
    at legacyClient.setPowerStateTelNet (/usr/lib/node_modules/homebridge-denon-heos/index.js:1337:31)
    at legacyClient.setPowerStateLegacy (/usr/lib/node_modules/homebridge-denon-heos/index.js:1247:9)
    at Characteristic.On.emit (events.js:310:20)
    at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:310:20)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:310:20)`

What am I doing wrong?

My config:

`"platforms": [
        {
            "platform": "DenonAVR",
            "devices": [
                {
                    "name": "Denon Receiver",
                    "ip": "10.0.2.112",
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "SAT/CBL",
                            "name": "TV"
                        },
                        {
                            "inputID": "DVD",
                            "name": "Apple TV"
                        },
                        {
                            "inputID": "NET",
                            "name": "Internet Radio"
                        },
                        {
                            "inputID": "AUX1",
                            "name": "AUX"
                        }
                    ]
                }
            ],
            "switches": [
                {
                    "name": "AVR on Apple TV",
                    "ip": "10.0.2.112",
                    "inputID": "DVD",
                    "pollAllInput": false
                },
                {
                    "name": "AVR on TV",
                    "ip": "10.0.2.112",
                    "inputID": "SAT/CBL"
                }
            ],
            "volumeControl": [
                {
                    "name": "Receiver Volume",
                    "ip": "10.0.2.112",
                    "volumeLimit": 60
                }
            ]
        }

**Comment by Martvvliet** [comment]
It is fixed?

**Comment by morphix9** [comment]
Yes. My fault! :D

**Comment by Martvvliet** [comment]
Great :) enjoy.

**Comment by twistedpixel** [comment]
I’m having this issue for the past few days. Do you remember how you fixed this?
