### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by morphix9** [Martvvliet/homebridge-denon-heos#33]
`Load hombridge-denon-heos.DenonAVR
[4/26/2020, 10:05:37] TypeError: Cannot read property 'debugTrace' of null
    at new denonClient (/usr/lib/node_modules/homebridge-denon-heos/index.js:74:20)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47`

**Comment by Martvvliet** [comment]
Should be fixed in 2.4.1. This happened when no config was setup. Thnx for posting issue.

**Comment by morphix9** [comment]
Yes, my fault ;D
