### ISSUE TITLE
Issue connecting to Denon

### ISSUE THREAD

**Issue by AdamZA1** [Martvvliet/homebridge-denon-heos#49]
Hello,

Have had my Denon set up in Homebridge flawlessly for a couple of weeks now, but today I have started getting No Response in HomeKit and this error in my Homebridge log:

    [6/3/2020, 3:33:44 PM] [DenonAVR] Cannot connect
    (node:19813) UnhandledPromiseRejectionWarning: Error: Cannot connect
        at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/telnet-client/lib/index.js:87:25)
        at Object.onceWrapper (events.js:411:28)
        at Socket.emit (events.js:305:20)
        at Socket._onTimeout (net.js:477:8)
        at listOnTimeout (internal/timers.js:537:17)
        at processTimers (internal/timers.js:481:7)
    
    (node:19813) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
    (node:19813) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    (node:19813) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'attempts' of undefined
        at connect (/usr/local/lib/node_modules/homebridge-denon-heos/index.js:740:2)
        at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-denon-heos/index.js:591:17)
        at listOnTimeout (internal/timers.js:537:17)
        at processTimers (internal/timers.js:481:7)
    
    (node:19813) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

Any ideas what it may be? Nothing has changed in the config and the Denon still works with the official Denon app.

Thanks in advance.

**Comment by AdamZA1** [comment]
Edit: solved after restarting network adapter

**Comment by Martvvliet** [comment]
Great. Thanks for posting. Enjoy the plugin :)
